pub const CREATE_IDENTITY_TYPE: &str = r#"
CREATE TYPE identity_type_enum AS ENUM ('Email', 'Phone');
"#;

pub const CREATE_USER_TABLE: &str = r#"
CREATE TABLE "user_table" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  identity varchar(128) NOT NULL UNIQUE,
  identity_type identity_type_enum NOT NULL,

  first_name varchar(128) NOT NULL,
  last_name varchar(128),

  -- Auth
  pwd varchar(256),
  -- pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  -- token_salt uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Timestamps
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);
"#;